# The Site Configuration

title: 71stars 블로그
author: "김기성"
description: "AI와 자동화의 만남"
theme: minima

# The language of the webpage
lang: ko

# Change to your timezone
timezone: Asia/Seoul

# Fill in the protocol & hostname for your site.
url: "https://saway126.github.io"

github:
  username: saway126

social:
  name: 71stars
  email: your_email@example.com
  links:
    - https://github.com/saway126

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID

# The base URL of your site
baseurl: ""

# Exclude files from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - backup
  - vendor
  - .sass-cache
  - node_modules
