source "https://rubygems.org"
gem "jekyll", "~> 3.9.3"
gem "jekyll-paginate"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "csv"
gem "base64"
gem "logger"
gem "bigdecimal"
gem "tzinfo"
gem "tzinfo-data"
gem "kramdown-parser-gfm"
