source "https://rubygems.org"
gem "jekyll", "~> 4.3.2"
gem "jekyll-paginate"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "csv"
gem "base64"
gem "tzinfo"
gem "tzinfo-data"
gem "logger"